// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core_user.sql

package db

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)
FROM core_user
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO core_user (role_id, name, email, password, status, uuid)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, created_at, deleted_at, updated_at, role_id, name, email, password, status, uuid
`

type CreateUserParams struct {
	RoleID   int64  `json:"role_id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Status   string `json:"status"`
	Uuid     string `json:"uuid"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CoreUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.RoleID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Status,
		arg.Uuid,
	)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Status,
		&i.Uuid,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, deleted_at, updated_at, role_id, name, email, password, status, uuid
FROM core_user
WHERE email = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (CoreUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Status,
		&i.Uuid,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, deleted_at, updated_at, role_id, name, email, password, status, uuid
FROM core_user
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (CoreUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Status,
		&i.Uuid,
	)
	return i, err
}

const getUserByRole = `-- name: GetUserByRole :many
SELECT id, created_at, deleted_at, updated_at, role_id, name, email, password, status, uuid
FROM core_user
WHERE role_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByRole(ctx context.Context, roleID int64) ([]CoreUser, error) {
	rows, err := q.db.Query(ctx, getUserByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreUser{}
	for rows.Next() {
		var i CoreUser
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.RoleID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Status,
			&i.Uuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, created_at, deleted_at, updated_at, role_id, name, email, password, status, uuid
FROM core_user
WHERE uuid = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByUUID(ctx context.Context, uuid string) (CoreUser, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, uuid)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Status,
		&i.Uuid,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, created_at, deleted_at, updated_at, role_id, name, email, password, status, uuid
FROM core_user
WHERE deleted_at IS NULL
ORDER BY id LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]CoreUser, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreUser{}
	for rows.Next() {
		var i CoreUser
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.RoleID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Status,
			&i.Uuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE core_user
SET deleted_at = now(),
    updated_at = now()
WHERE uuid = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, uuid string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE core_user
SET name       = $2,
    email      = $3,
    role_id    = $4,
    status     = $5,
    updated_at = now()
WHERE uuid = $1
  AND deleted_at IS NULL RETURNING id, created_at, deleted_at, updated_at, role_id, name, email, password, status, uuid
`

type UpdateUserParams struct {
	Uuid   string `json:"uuid"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	RoleID int64  `json:"role_id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (CoreUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Uuid,
		arg.Name,
		arg.Email,
		arg.RoleID,
		arg.Status,
	)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Status,
		&i.Uuid,
	)
	return i, err
}
