// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core_user_role.sql

package db

import (
	"context"
)

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, created_at, deleted_at, updated_at, role_name, role_level
FROM core_user_role
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetRoleByID(ctx context.Context, id int64) (CoreUserRole, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i CoreUserRole
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.RoleName,
		&i.RoleLevel,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, created_at, deleted_at, updated_at, role_name, role_level
FROM core_user_role
WHERE deleted_at IS NULL
ORDER BY role_level
`

func (q *Queries) ListRoles(ctx context.Context) ([]CoreUserRole, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreUserRole{}
	for rows.Next() {
		var i CoreUserRole
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.RoleName,
			&i.RoleLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
