// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CoreUser, error)
	GetRoleByID(ctx context.Context, id int64) (CoreUserRole, error)
	GetUserByEmail(ctx context.Context, email string) (CoreUser, error)
	GetUserByID(ctx context.Context, id int64) (CoreUser, error)
	GetUserByRole(ctx context.Context, roleID int64) ([]CoreUser, error)
	GetUserByUUID(ctx context.Context, uuid string) (CoreUser, error)
	ListRoles(ctx context.Context) ([]CoreUserRole, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]CoreUser, error)
	SoftDeleteUser(ctx context.Context, uuid string) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (CoreUser, error)
}

var _ Querier = (*Queries)(nil)
